### PR TITLE
Fixed #535 : setting documentIDs not working in Push replication

### LINKED ISSUE #535: The replicator's setDocIds method doesn't filter the documents to push
The Replication class has a setDocIds method to provide a list of doc ids to only sync those docs in a push replication.

I believe this method is not documented on the mobile portal yet. The only time I saw it was used is in the PhotoDrop app @pasin wrote to selectively push the selected pictures.

I was wondering if it worked with Lite -> SG replication as well.

See this example to reproduce https://github.com/jamiltz/ReplicationFilter#array-of-document-ids

### PR DESCRIPTION
**Pull request by pasin**
Implemented documentID filtering for push replication.

#535

### CODE REVIEW

File: src/main/java/com/couchbase/lite/replicator/Replication.java [hunk 1]
```diff
@@ -641,16 +634,16 @@ public void setFilter(String filterName) {
      * Sets the documents to specify as part of the replication.
      */
     @InterfaceAudience.Public
-    public void setDocIds(List<String> docIds) {
+    public void setDocumentIDs(List<String> docIds) {
```
Comment (hideki) [inline src/main/java/com/couchbase/lite/replicator/Replication.java]: setDocIds is public API, and it is documented with 
```
public List<String> getDocIds()
public void setDocIds(List<String> docIds)
```
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/couchbase-lite/replication/replication/index.html#string-docids--get-set-

This method signature should not be changed.

File: src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java [hunk 2]
```diff
@@ -965,6 +967,29 @@ public void setFilter(String filterName) {
         this.filterName = filterName;
     }
 
+    /**
+     * Get replicator filter. If the replicator is a pull replicator,
+     * calling this method will return null.
+     *
+     * This is equivalent to CBL_ReplicatorSettings's compilePushFilterForDatabase:status:.
+     */
+    public ReplicationFilter compilePushReplicationFilter() {
```
Comment (hideki) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: should this method be declared in PusherInternal?

File: src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java [hunk 3]
```diff
@@ -974,14 +999,14 @@ public void setFilter(String filterName) {
     /**
      * Gets the documents to specify as part of the replication.
      */
-    public List<String> getDocIds() {
+    public List<String> getDocumentIDs() {
```
Comment (hideki) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: If we keep current API name, this method signature should not be changed.

File: src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java [hunk 4]
```diff
@@ -974,14 +999,14 @@ public void setFilter(String filterName) {
...
         return documentIDs;
     }
 
     /**
      * Sets the documents to specify as part of the replication.
      */
-    public void setDocIds(List<String> docIds) {
+    public void setDocumentIDs(List<String> docIds) {
```
Comment (hideki) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: same with above

File: src/main/java/com/couchbase/lite/replicator/Replication.java (hunk 1 above)
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/Replication.java]: iOS has documentIDs. I will change back to DocIds and let @zgramana review the discrepency.

File: src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java (hunk 2 above)
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: No because it is used in Replication.java as well. We should adopt ReplicationSettings from iOS.

https://github.com/couchbase/couchbase-lite-java-core/issues/870

**Comment by pasin** [comment]
I fixed the API. Could you please re-review?
