### PR TITLE
Fixed #1227 - Port: Crash when saving, conflict generated and infinit…

### LINKED ISSUE #1227: Port: Crash when saving, conflict generated and infinite replication loop
https://github.com/couchbase/couchbase-lite-ios/issues/1217

### PR DESCRIPTION
**Pull request by hideki**
…e replication loop

- iOS implementation: https://github.com/couchbase/couchbase-lite-ios/pull/1237

### CODE REVIEW

File: src/main/java/com/couchbase/lite/Database.java [hunk 1]
```diff
@@ -1699,6 +1701,9 @@ public RevisionInternal put(String docID,
                 (properties.containsKey("_deleted") &&
                         ((Boolean) properties.get("_deleted")).booleanValue());
 
+        Log.v(TAG, "%s _id=%s, _rev=%s (allowConflict=%s)", (deleting ? "DELETE" : "PUT"),
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/Database.java]: IIRC, I think you can use %b for boolean to show true / false.

File: src/main/java/com/couchbase/lite/store/SQLiteStore.java [hunk 2]
```diff
@@ -2315,7 +2339,7 @@ protected int pruneRevsToMaxDepth(int maxDepth) throws CouchbaseLiteException {
         try {
             beginTransaction();
             for (Long docNumericID : toPrune.keySet())
-                outPruned += pruneDocument(docNumericID, toPrune.get(docNumericID).intValue() + 1);
+                outPruned += pruneDocument("?", docNumericID, toPrune.get(docNumericID).intValue() + 1);
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/store/SQLiteStore.java]: What is "?" ? Can you give some info?

File: src/main/java/com/couchbase/lite/store/SQLiteStore.java [hunk 3]
```diff
@@ -2326,10 +2350,71 @@ protected int pruneRevsToMaxDepth(int maxDepth) throws CouchbaseLiteException {
     }
 
     // Returns the number of revisions pruned.
-    protected int pruneDocument(long docNumericID, int minGenToKeep) {
-        String minIDToKeep = String.format("%d-", minGenToKeep);
-        String[] deleteArgs = {Long.toString(docNumericID), minIDToKeep};
-        return storageEngine.delete("revs", "doc_id=? AND revid < ? AND current=0", deleteArgs);
+    protected int pruneDocument(String docID, long docNumericID, int minGenToKeep) {
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/store/SQLiteStore.java]: I don't see docID getting used in this method? Does it really need docID param?

File: src/main/java/com/couchbase/lite/store/SQLiteStore.java (hunk 2 above)
Comment (pasin) [inline src/main/java/com/couchbase/lite/store/SQLiteStore.java]: I see. There is no docID.

Comment (hideki) [inline src/main/java/com/couchbase/lite/store/SQLiteStore.java]: In iOS implementation, pruneDocument()'s docID parameter is only used for logging.
https://github.com/couchbase/couchbase-lite-ios/blob/2d6e6355e46cacab46d404bfb5e7ceaa1a92a7c9/Source/CBL_SQLiteStorage.m#L2093

For Java, we could remove this parameter.

File: src/main/java/com/couchbase/lite/store/SQLiteStore.java (hunk 3 above)
Comment (hideki) [inline src/main/java/com/couchbase/lite/store/SQLiteStore.java]: no

File: src/main/java/com/couchbase/lite/store/SQLiteStore.java (hunk 2 above)
Comment (pasin) [inline src/main/java/com/couchbase/lite/store/SQLiteStore.java]: Do you plan to remove docID param or add some logs that show docID?

Comment (hideki) [inline src/main/java/com/couchbase/lite/store/SQLiteStore.java]: To be consistent with iOS, CBL Java can keep docID param. But it might not be used.
Do you have suggestion?

Comment (pasin) [inline src/main/java/com/couchbase/lite/store/SQLiteStore.java]: Can we add the following logs that use docID? Are those logs not applicable for android?

https://github.com/couchbase/couchbase-lite-ios/blob/2d6e6355e46cacab46d404bfb5e7ceaa1a92a7c9/Source/CBL_SQLiteStorage.m#L2118-L2119

https://github.com/couchbase/couchbase-lite-ios/blob/2d6e6355e46cacab46d404bfb5e7ceaa1a92a7c9/Source/CBL_SQLiteStorage.m#L2141
