### PR TITLE
Fixed #717 - testContinuousPushReplicationGoesIdleTooSoon causes nati…

### LINKED ISSUE #717: testContinuousPushReplicationGoesIdleTooSoon causes native crash if unit test run from command line on OSX
Command:

`$ ./gradlew connectedAndroidTest --info`

Log:
```
com.couchbase.lite.replicator.ReplicationTest > testContinuousPushReplicationGoesIdleTooSoon[Google Nexus 4 - 4.4.4 - API 19 - 768x1280 - 4.4.4] FAILED 
Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Process crashed.''. Check device logcat for details
Tests on Google Nexus 4 - 4.4.4 - API 19 - 768x1280 - 4.4.4 failed: Instrumentation run failed due to 'Process crashed.'
deleteDir(/Users/hideki/github/couchbase-lite-android/build/reports/androidTests/connected) returned: true
:connectedDebugAndroidTest FAILED
:connectedDebugAndroidTest (Thread[main,5,main]) completed. Took 7 mins 18.596 secs.
```

### PR DESCRIPTION
**Pull request by hideki**
…ve crash if unit test run from command line on OSX

- Native crash issue was addressed by couchbaselabs/couchbase-lite-java-forestdb/pull/5
- However, root cause of this issue still caused the test failure.
- Some of database access is from different threads. For example, threads run RemoteRequest. Callback codes from RemoteRequest access database.
- To make callback codes access database synchronously, add synchronized block for some database accessing codes.
- Currently I knows this two methods caused invalid database access, maybe more methods should be synchronized.

### CODE REVIEW

File: src/main/java/com/couchbase/lite/Database.java [hunk 1]
```diff
@@ -1194,7 +1194,9 @@ public RevisionInternal getDocument(String docID, String revID, boolean withBody
 
     @InterfaceAudience.Private
     public RevisionInternal loadRevisionBody(RevisionInternal rev) throws CouchbaseLiteException {
-        return store.loadRevisionBody(rev);
+        synchronized(store) {
+            return store.loadRevisionBody(rev);
+        }
     }
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/Database.java]: As we only synchronize the store on loadRevisionBody and getRevisionHistory method, I think we should put some comments here and explain why we are doing it on these 2 methods.
