### PR TITLE
Fixed #635 - Jackson deserialization exception

### LINKED ISSUE #635: Jackson deserialization exception
Appears when waiting for changes.
```
E/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@242261ec: Exception in change tracker
    org.codehaus.jackson.JsonParseException: Unexpected end-of-input: expected close marker for ARRAY (from [Source: org.apache.http.conn.EofSensorInputStream@1e95fd5f; line: 1, column: 1])
```
The Netscaler proxy between the WAN and SG may potentially be over-aggressively buffering `_changes` feed response stream due to gzip + chunked transfer. @snej dealt with [a similar, if not the same, issue in iOS](https://github.com/couchbase/couchbase-lite-ios/commit/88f59f729ebff0dad7bdd9e1b2c64f80347fa086), which may possibly be helpful. The reporter is going to try to bypass the Netscaler to see if that isolates the issue.

### PR DESCRIPTION
**Pull request by hideki**
- If ChangeTracker fails with incomplete JSON or 0 byte contents, it will retry with adjusted heartbeat value.

### CODE REVIEW

File: src/main/java/com/couchbase/lite/replicator/ChangeTracker.java [hunk 1]
```diff
@@ -340,26 +344,40 @@ public void process(HttpRequest request, HttpContext context) throws HttpExcepti
...
+                                    // server was waiting for a change to send, due to lack of activity.
+                                    // Lower the heartbeat time to work around this, and reconnect:
+                                    this.heartBeatSeconds = Math.min(this.heartBeatSeconds, (int) (elapsed * 0.75));
+                                    Log.v(Log.TAG_CHANGE_TRACKER, "%s: Starting new longpoll", this);
+                                    backoff.resetBackoff();
+                                    continue;
+                                } else {
+                                    Log.d(Log.TAG_CHANGE_TRACKER, "%s: Change tracker calling stop (LongPoll)", this);
+                                    client.changeTrackerFinished(this);
+                                    break;
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/ChangeTracker.java]: In iOS, this case is treated as a socket error, from the code here, it's not clear if this will get handled as an error or not.

```
// Response data was truncated. This has been reported as an intermittent error
            // (see TouchDB issue #241). Treat it as if it were a socket error -- i.e. pause/retry.
            [self failedWithError: [NSError errorWithDomain: NSURLErrorDomain code: NSURLErrorNetworkConnectionLost userInfo: nil]];
```

Comment (hideki) [inline src/main/java/com/couchbase/lite/replicator/ChangeTracker.java]: Hi @pasin, Thank you very much for reviewing PR. I will check if it is necessary to set error for this scenario. If necessary, I will update the codes. Thanks!

Comment (hideki) [inline src/main/java/com/couchbase/lite/replicator/ChangeTracker.java]: Ticket for ChangeTracker error handling enhancement
https://github.com/couchbase/couchbase-lite-java-core/issues/639
