### PR TITLE
Fixed #1637 - 1.x: RejectedExecutionException is through from Replicator

### LINKED ISSUE #1637: 1.x: RejectedExecutionException is through from Replicator
The following line of codes allows to shutdown the executor service during submitting the task to Executor.
```java
  if (executor != null && !executor.isShutdown())
    executor.shutdown();
```
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java#L1478-L1479

Links:
- https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Executor.html
- https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadPoolExecutor.html
- http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b27/java/util/concurrent/ScheduledThreadPoolExecutor.java#ScheduledThreadPoolExecutor.shutdown%28%29

### PR DESCRIPTION
**Pull request by hideki**
- `Executor.submit(...)` throws `RejectedExecutionException` if `Executor` is shutdown. So we had two choices. One is apply `try-catch` block for all Executor.submit(...) method. Another one is make Executor.submit(...), schedule(...), shutdown(), etc methods are thread safe. I picked second choice because already CBL codes has tried to be thread-safe with Executor services.

### CODE REVIEW

**Comment by hideki** [comment]
@pasin please re-review this PR? thanks!

File: src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java [hunk 1]
```diff
@@ -229,20 +228,22 @@ public void triggerGoOnline() {
...
-                executor.submit(new Runnable() {
-                    @Override
-                    public void run() {
-                        try {
-                            Log.d(Log.TAG_SYNC, "firing trigger: %s", trigger);
-                            stateMachine.fire(trigger);
-                        } catch (Exception e) {
-                            Log.i(Log.TAG_SYNC, "Error in StateMachine.fire(trigger): %s", e.getMessage());
-                            throw new RuntimeException(e);
+        if (executor != null) {
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: Need need to check null, right?

File: src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java [hunk 2]
```diff
@@ -190,7 +190,6 @@
     protected void finalize() throws Throwable {
         if (executor != null && !executor.isShutdown()) {
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: no need to check null here?

Comment (hideki) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: `finalize()` method is called even though constructor fails. the executor is instantiated in the constructor.

File: src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java (hunk 1 above)
Comment (hideki) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: I will fix this.

**Comment by hideki** [comment]
please review this again. Thanks!
