### PR TITLE
Fixed #742 Refactor Store.open and Database.open method signature

### LINKED ISSUE #742: Make Store.open() method return void and throw exception when having an error
Per discussion with @hideki, we should make this method to return void and throw exception when there is an error (instead of mixing returning true/false with throwing an exception).

### PR DESCRIPTION
**Pull request by pasin**
Made Store.open and Database.open to return void and throw CouchbaseLiteException.

#742

### CODE REVIEW

File: src/main/java/com/couchbase/lite/store/SQLiteStore.java [hunk 1]
```diff
@@ -197,77 +210,84 @@ public synchronized boolean open() throws CouchbaseLiteException {
...
                 // monotonically increasing, never reused. See <http://www.sqlite.org/autoinc.html>)
-
                 if (!isNew) {
-                    Log.w(TAG, "Database version (%d) is older than I know how to work with",
-                            dbVersion);
-                    storageEngine.close();
-                    return false;
+                    String message = "Database version " + dbVersion +
+                            " is older than I know how to work with";
+                    Log.e(TAG, message, dbVersion);
```
Comment (hideki) [inline src/main/java/com/couchbase/lite/store/SQLiteStore.java]: In format, no %d. But method is given dbVersion as third parameter. I am not sure what kind of problem this might cause.

File: src/main/java/com/couchbase/lite/DatabaseUpgrade.java [hunk 2]
```diff
@@ -83,15 +83,10 @@ protected boolean importData() {
...
-            Throwable error = null;
             try {
-                isOpen = db.open();
+                db.open();
             } catch (CouchbaseLiteException e) {
-                error = e;
-            }
-            if (!isOpen) {
-                Log.e(TAG, "Upgrade failed:  Couldn't open new db: %s", db.toString(), error);
+                Log.e(TAG, "Upgrade failed:  Couldn't open new db: %s", db.toString(), e);
```
Comment (hideki) [inline src/main/java/com/couchbase/lite/DatabaseUpgrade.java]: Original code was wrong. Third parameter should be Throwable.
```java
    public static void e(String tag, String formatString, Throwable tr, Object... args) {
        if (logger != null && isLoggingEnabled(tag, ERROR)) {
            try {
                logger.e(tag, String.format(formatString, args), tr);
            } catch (Exception e) {
                logger.e(tag, String.format("Unable to format log: %s", formatString), e);
            }
        }
    }
```

File: src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java [hunk 3]
```diff
@@ -748,7 +748,10 @@ public void onCompletion(HttpResponse httpResponse, Object result, Throwable e)
                         remoteCheckpoint = body;
                         boolean isOpen = false;
                         try {
-                            isOpen = (db != null && db.open());
+                            if (db != null) {
+                                db.open();
+                                isOpen = true;
+                            }
                         } catch (CouchbaseLiteException ex) {
                             Log.w(Log.TAG_SYNC, "%s: Cannot open the database", this, ex);
```
Comment (hideki) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: Third parameter should be Throwable.

File: src/main/java/com/couchbase/lite/store/SQLiteStore.java [hunk 4]
```diff
@@ -197,77 +210,84 @@ public synchronized boolean open() throws CouchbaseLiteException {
 
         // Incompatible version changes increment the hundreds' place:
         if (dbVersion >= 200) {
-            Log.e(TAG, "Database: Database version (%d) is newer than I know how to work with",
-                    dbVersion);
             storageEngine.close();
-            return false;
+            String message = "Database version " + dbVersion +
+                    " is newer than I know how to work with";
+            Log.e(TAG, message, dbVersion);
```
Comment (hideki) [inline src/main/java/com/couchbase/lite/store/SQLiteStore.java]: No %d in format. But third parameter is given.

File: src/main/java/com/couchbase/lite/DatabaseUpgrade.java (hunk 2 above)
Comment (pasin) [inline src/main/java/com/couchbase/lite/DatabaseUpgrade.java]: I have noticed that DatabaseUpgrade.java has several Log method calls that I'm not sure about the original attention. For example,

```
Log.w(TAG, "Couldn't import local doc '%s': '%s'", docID, e);
```
There are several like the example above. All of these should be revise.

**Comment by pasin** [comment]
Thanks for the review. I have pushed up the changes. Please re-review.

File: src/main/java/com/couchbase/lite/DatabaseUpgrade.java (hunk 2 above)
Comment (hideki) [inline src/main/java/com/couchbase/lite/DatabaseUpgrade.java]: I guess `e` intents `e.toString()`.

Comment (pasin) [inline src/main/java/com/couchbase/lite/DatabaseUpgrade.java]: Why don't just put e in the 3rd parameter? Anyway I think this is a bit off topic of this PR.
