### PR TITLE
Fix #328

### LINKED ISSUE #328: Excessive checkpointing during push replication
Noticed while investigating https://github.com/couchbase/couchbase-lite-java-core/issues/313

To reproduce:

* Run [office-radar-android](https://github.com/tleyden/office-radar-android) from scratch
* Re-run app 
* During push, excessive number of "PUT checkpoint" requests (as compared to iOS)

### PR DESCRIPTION
**Pull request by hideki**
- To change the rule of sending PUT /{db}/_local/xxxx to follow iOS implementation
- Cleanup unused codes. By shifting to StateMachine, some variables and methods which are from iOS code were not used.

### CODE REVIEW

File: src/main/java/com/couchbase/lite/replicator/PullerInternal.java [hunk 1]
```diff
@@ -566,7 +562,7 @@ public int compare(RevisionInternal reva, RevisionInternal revb) {
 
     private void revisionFailed(RevisionInternal rev, Throwable throwable) {
         if (Utils.isTransientError(throwable)) {
-            revisionFailed();  // retry later
+            // retry later
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/PullerInternal.java]: Maybe we shouldn't keep this if block as it does nothing.

File: src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java [hunk 2]
```diff
@@ -1314,11 +1319,6 @@ protected void retryReplicationIfError(){
         }
     }
 
-    // TODO: not used, please remove
-    protected void updateActive() {
-        Log.v(Log.TAG_SYNC, "%s: updateActive() called", this);
-    }
-
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: As the updateAction() method is now removed, we should update some log messages in the file that say something about calling updateActive() method to avoid confusion.
