### PR TITLE
Fixed #1061 - NullPointerException in Implementation of Validator

### LINKED ISSUE #1061: NullPointerException in Implementation of Validator
Scenario : Implement a Validator that only log information about the revision that is about to be validated. Especially one must try to log the list of key that changed using the ValidationContext.getChangedKeys(). Once added to the database the validator will generate a NullPointerException when calling in ValidationContextImpl.java the following code : 
Map<String, Object> cur = getCurrentRevision().getProperties();
Also this NullPointerException gets thrown when calling isDeleted() from the document that is being validated in the current revision.

### PR DESCRIPTION
**Pull request by hideki**
In case of creating new document or deleting the document, Validator could cause NPE if access getKeyChanges() or isDeleted(). So added null check.

### CODE REVIEW

File: src/main/java/com/couchbase/lite/ValidationContextImpl.java [hunk 1]
```diff
@@ -42,16 +42,22 @@ public SavedRevision getCurrentRevision() {
...
             changedKeys = new ArrayList<String>();
-            Map<String, Object> cur = getCurrentRevision().getProperties();
+            Map<String, Object> cur = null;
+            if (getCurrentRevision() != null)
+                cur = getCurrentRevision().getProperties();
             Map<String, Object> nuu = newRev.getProperties();
-            for (String key : cur.keySet()) {
-                if (!cur.get(key).equals(nuu.get(key)) && !key.equals("_rev")) {
-                    changedKeys.add(key);
+            if (null != null) {
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/ValidationContextImpl.java]: Should be nuu != null.

File: src/main/java/com/couchbase/lite/ValidationContextImpl.java [hunk 2]
```diff
@@ -42,16 +42,22 @@ public SavedRevision getCurrentRevision() {
...
+                if (cur != null) {
+                    for (String key : cur.keySet()) {
+                        if (!cur.get(key).equals(nuu.get(key)) && !key.equals("_rev")) {
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/ValidationContextImpl.java]: Would it be possible that cur.get(key) returns null?

**Comment by hideki** [comment]
@pasin Please re-review this. Thank you very much for catching my mistake.
