### PR TITLE
Fixed #738 (ViewsTest failures)

### LINKED ISSUE #738: two unit tests of ViewsTest fail
-  testViewQuery (SQLIte) (Java and Android)
- testDeleteView (SQLIte) (Java and Android)

### PR DESCRIPTION
**Pull request by hideki**
- Added CountDown class for unonymous block
- Implemented missing logics for regularQuery to fix ViewsTest

### CODE REVIEW

File: src/main/java/com/couchbase/lite/store/SQLiteViewStore.java [hunk 1]
```diff
@@ -459,19 +461,22 @@ public void emit(Object key, Object value) {
...
+            tmpLimit = options.getLimit();
+            tmpSkip = options.getSkip();
+            if(tmpLimit == 0)
+                return new ArrayList<QueryRow>(); // empty result set
             options.setLimit(QueryOptions.QUERY_OPTIONS_DEFAULT_LIMIT);
             options.setSkip(0);
         }
 
+        final CountDown skip = new CountDown(tmpSkip);
+        final CountDown limit = new CountDown(tmpLimit);;
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/store/SQLiteViewStore.java]: There are two semicolons.
