### PR TITLE
Fixed #1605 - 1.x: peer to peer replication with attachments does not…

### LINKED ISSUE #1605: 1.x: peer to peer replication with attachments does not work with android client
I tested peer to peer replication with attachment between net-mono and android device using the below command:
```
pytest -s -k test_peer_2_peer_sanity_push --liteserv-one-platform=net-mono 
--liteserv-one-version=1.4-50 --liteserv-one-host=<net_mono_ip> 
--liteserv-one-port=51000 --liteserv-one-storage-engine=SQLite 
--liteserv-two-platform=android --liteserv-two-version=1.4-44 
--liteserv-two-host=<Android_IP> --liteserv-two-port=52000 
--liteserv-two-storage-engine=SQLite  testsuites/listener/shared/client_client/
```

Without attachment, replication works fine. With attachment, replication does not work. I see the below trace in the logs:
```
02-27 15:46:47.456  2492  2534 W Router  : Router unable to route request to do_PUT_Document
02-27 15:46:47.456  2492  2534 W Router  : java.lang.reflect.InvocationTargetException
02-27 15:46:47.456  2492  2534 W Router  : 	at java.lang.reflect.Method.invoke(Native Method)
02-27 15:46:47.456  2492  2534 W Router  : 	at com.couchbase.lite.router.Router.start(Router.java:560)
02-27 15:46:47.456  2492  2534 W Router  : 	at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:147)
02-27 15:46:47.456  2492  2534 W Router  : 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
02-27 15:46:47.456  2492  2534 W Router  : 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2408)
02-27 15:46:47.456  2492  2534 W Router  : 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2330)
02-27 15:46:47.456  2492  2534 W Router  : 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:2110)
02-27 15:46:47.456  2492  2534 W Router  : 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1238)
02-27 15:46:47.456  2492  2534 W Router  : 	at java.lang.Thread.run(Thread.java:761)
02-27 15:46:47.456  2492  2534 W Router  : Caused by: com.couchbase.lite.CouchbaseLiteException, Status: 406 (HTTP 406 not_acceptable)
02-27 15:46:47.456  2492  2534 W Router  : 	at com.couchbase.lite.router.Router.getBodyAsDictionary(Router.java:247)
02-27 15:46:47.456  2492  2534 W Router  : 	at com.couchbase.lite.router.Router.do_PUT_Document(Router.java:2364)
02-27 15:46:47.456  2492  2534 W Router  : 	... 9 more
```

It seems like android listener is not handling the multipart request.

### PR DESCRIPTION
**Pull request by hideki**
… work with android client

- `PUT /{db}/{docID}` REST API did not support a multipart content.

### CODE REVIEW

File: src/main/java/com/couchbase/lite/util/Utils.java [hunk 1]
```diff
@@ -282,6 +285,25 @@ public static boolean isGzip(String contentEncoding) {
...
+        for (String str : list) {
+            if (sb.length() != 0)
+                sb.append(separator);
+            sb.append(str);
+        }
+        return sb.toString();
+    }
+
+    public static Map<String, String> headersToMap(Map<String, List<String>> headers) {
+        List<String>a = new ArrayList<String>();
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/util/Utils.java]: No use of a variable.

File: src/main/java/com/couchbase/lite/util/Utils.java [hunk 2]
```diff
@@ -282,6 +285,25 @@ public static boolean isGzip(String contentEncoding) {
...
+        Map<String, String> map = new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/util/Utils.java]: Just a question. Does it need to be in-order?

Comment (hideki) [reply src/main/java/com/couchbase/lite/util/Utils.java]: https://tools.ietf.org/html/rfc2616#section-4.2
>The order in which header fields with differing field names are
   received is not significant. However, it is "good practice" to send
   general-header fields first, followed by request-header or response-
   header fields, and ending with the entity-header fields.

So not necessary to be alphabetical order.
