### PR TITLE
Fixed #452 - Application does not terminate after having network error

### LINKED ISSUE #452: Error after close DB client
https://github.com/couchbase/couchbase-lite-java/issues/52

```java
private void shutdownDatabase() {
        push.goOffline();
        pull.goOffline();
        pull.stop();
        push.stop();
        database.close();
        manager.close();
    }
````
in log:
```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@32f4b68 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@5263919f[Shutting down, pool size = 1, active threads = 1, queued tasks = 6, completed tasks = 15]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
	at com.couchbase.lite.replicator.PullerInternal.changeTrackerStopped(PullerInternal.java:766)
	at com.couchbase.lite.replicator.ChangeTracker.stopped(ChangeTracker.java:512)
	at com.couchbase.lite.replicator.ChangeTracker.stop(ChangeTracker.java:498)
	at com.couchbase.lite.replicator.PullerInternal.goOffline(PullerInternal.java:994)
	at com.couchbase.lite.replicator.ReplicationInternal$15.doIt(ReplicationInternal.java:1101)
	at com.couchbase.lite.replicator.ReplicationInternal$15.doIt(ReplicationInternal.java:1098)
	at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:130)
	at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:127)
	at com.github.oxo42.stateless4j.StateRepresentation.executeEntryActions(StateRepresentation.java:123)
	at com.github.oxo42.stateless4j.StateRepresentation.enter(StateRepresentation.java:102)
	at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:199)
	at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:125)
	at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:191)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4579bbfb rejected from java.util.concurrent.ScheduledThreadPoolExecutor@5263919f[Shutting down, pool size = 1, active threads = 1, queued tasks = 3, completed tasks = 18]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
	at com.couchbase.lite.replicator.ReplicationInternal.notifyChangeListeners(ReplicationInternal.java:983)
	at com.couchbase.lite.replicator.ReplicationInternal.notifyChangeListenersStateTransition(ReplicationInternal.java:1138)
	at com.couchbase.lite.replicator.ReplicationInternal.access$400(ReplicationInternal.java:61)
	at com.couchbase.lite.replicator.ReplicationInternal$16.doIt(ReplicationInternal.java:1109)
	at com.couchbase.lite.replicator.ReplicationInternal$16.doIt(ReplicationInternal.java:1105)
	at com.github.oxo42.stateless4j.StateRepresentation.executeExitActions(StateRepresentation.java:130)
	at com.github.oxo42.stateless4j.StateRepresentation.exit(StateRepresentation.java:112)
	at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:197)
	at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:125)
	at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:191)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by hideki**
Problem:
- In case of failing the connection with server, CBL keeps retrying till retry counter reaches maximum. It blocks app terminates.

Solution:
- Give 60sec to ReplicationInternal to wait remoteRequestExecutor terminated
- Clean unused variable in RemoteRequest.java
- RemoteRequestRetry keeps trying even though replicator is shutting down. So Check requestExecutor status before retry.
- Added `shutdownAndAwaitTermination(ExecutorService, long)` for more flexibility

### CODE REVIEW

File: src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java [hunk 1]
```diff
@@ -278,7 +278,8 @@ public void databaseClosing() {
     protected void close() {
         // shutdown ScheduledExecutorService. Without shutdown, cause thread leak
         if (remoteRequestExecutor != null && !remoteRequestExecutor.isShutdown()) {
-            Utils.shutdownAndAwaitTermination(remoteRequestExecutor);
+            // Note: Time to wait is set 60 sec because RemoteRequest's socket timeout is set 60 seconds.
+            Utils.shutdownAndAwaitTermination(remoteRequestExecutor, 60);
         }
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: When a replicator is stopped, do all current remote requests get aborted as well? If YES, does aborting a request need to wait for the timeout?

Comment (hideki) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: No. The remote request is not aborted immediately. RemoteRequest is blocking till timeout which is 60 seconds. 

It seems HttpClient does not have cancel (abort) feature.
https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/

Comment (hideki) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: Solution to abort connection.

- `HttpClient.getConnectionManager().shutdown();` might make connection aborted
http://stackoverflow.com/questions/7140565/how-do-i-cancel-an-android-http-request

- https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/HttpClient.html#getConnectionManager()
- https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/conn/ClientConnectionManager.html#shutdown()

Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: http://developer.android.com/reference/org/apache/http/client/methods/AbortableHttpRequest.html
But HttpClient is not derived from that.

I saw this from the HttpClient.html you sent above:
```
This interface was deprecated in API level 22.
Please use openConnection() instead. Please visit this webpage for further details.
http://android-developers.blogspot.com/2011/09/androids-http-clients.html
```

Comment (hideki) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: Switch from HttpClient to openConneciton() is another big change. We can discuss it on Monday.

Lollipop SDK 5.0.x is API 21. And we need to to support all versions since API 9 SDK (2.?.?). 
So HttpClient will be deprecated, but for short term, `HttpClient.getConnectionManager().shutdown()` could be solution.

**Comment by pasin** [comment]
As discussed with @hideki, implementing HttpClient abortion is not trivial and requires a lot changes in the current architecture as the HttpClient is not exposed from the Future object and the RemoteRequest object doesn't get InterruptException upon shutting down the wore executor. The change will be postponed until we change from HttpClient to URLConnection.

File: src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java (hunk 1 above)
Comment (hideki) [inline src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java]: Switch to `openConnection()` and to support abort connection are tracked by different ticket. https://github.com/couchbase/couchbase-lite-java-core/issues/532
