### PR TITLE
Fix #771 InputStream not get closed in BlobStore.getBytesFromFile

### LINKED ISSUE #771: BloblStoreTest failed on Windows
See log below:
```
com.couchbase.lite.BlobStoreTest > testBasic STANDARD_ERROR
    Oct 01, 2015 4:45:10 AM com.couchbase.lite.util.SystemLogger d
    FINE: Database: Starting Manager version: devbuild
    Oct 01, 2015 4:45:10 AM com.couchbase.lite.util.SystemLogger w
    WARNING: Database: mustExist is true and db (cblite-test) does not exist
    Oct 01, 2015 4:45:10 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Opening com.couchbase.lite.Database[C:\Users\pasin\Git\couchbase-lite-java\data\data\com.couchbase.
lite.test\files\test\cblite-test.cblite2]
    Oct 01, 2015 4:45:10 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: AndroidSQLCipherStorageEngine{database=33fd6994}: Opened Android sqlite db
    Oct 01, 2015 4:45:10 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Begin transaction (level 0)
    Oct 01, 2015 4:45:10 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: calls optimizeSQLIndexes()
    Oct 01, 2015 4:45:10 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Committing transaction (level 0)
    Oct 01, 2015 4:45:13 AM com.couchbase.lite.util.SystemLogger v
    FINER: LiteTestCaseWithDB: tearDown
    Oct 01, 2015 4:45:14 AM com.couchbase.lite.util.SystemLogger d
    FINE: Database: Closing com.couchbase.lite.Manager@d804ac3
    Oct 01, 2015 4:45:14 AM com.couchbase.lite.util.SystemLogger d
    FINE: Database: Closed com.couchbase.lite.Manager@d804ac3
    Oct 01, 2015 4:45:14 AM com.couchbase.lite.util.SystemLogger e
    SEVERE: LiteTestCase: DURATION: testBasic: 3 sec - [SLOW]
    Oct 01, 2015 4:45:14 AM com.couchbase.lite.util.SystemLogger e
    SEVERE: LiteTestCaseWithDB: DURATION: testBasic: 3 sec
    Oct 01, 2015 4:45:14 AM com.couchbase.lite.util.SystemLogger v
    FINER: LiteTestCaseWithDB: setUp
    Oct 01, 2015 4:45:14 AM com.couchbase.lite.util.SystemLogger d
    FINE: Database: Starting Manager version: devbuild
    Oct 01, 2015 4:45:14 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Opening com.couchbase.lite.Database[C:\Users\pasin\Git\couchbase-lite-java\data\data\com.couchbase.
lite.test\files\test\cblite-test.cblite2]
    Oct 01, 2015 4:45:14 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: AndroidSQLCipherStorageEngine{database=7fe0813a}: Opened Android sqlite db
    Oct 01, 2015 4:45:14 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Begin transaction (level 0)
    Oct 01, 2015 4:45:14 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Committing transaction (level 0)
    Oct 01, 2015 4:45:14 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Opening com.couchbase.lite.Database[C:\Users\pasin\Git\couchbase-lite-java\data\data\com.couchbase.
lite.test\files\test\cblite-test.cblite2]
    Oct 01, 2015 4:45:14 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: AndroidSQLCipherStorageEngine{database=50211475}: Opened Android sqlite db
    Oct 01, 2015 4:45:14 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Begin transaction (level 0)
    Oct 01, 2015 4:45:14 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: calls optimizeSQLIndexes()
    Oct 01, 2015 4:45:14 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Committing transaction (level 0)
    Oct 01, 2015 4:45:15 AM com.couchbase.lite.util.SystemLogger i
    INFO: LiteTestCaseWithDB: ---- Now enabling attachment encryption ----
    Oct 01, 2015 4:45:15 AM com.couchbase.lite.util.SystemLogger e
    SEVERE: Database: BlobStore: Blob store was corrupted. Encryption marker file was not found

com.couchbase.lite.BlobStoreTest > testBasic FAILED
    com.couchbase.lite.CouchbaseLiteException
        at com.couchbase.lite.BlobStore.verifyExistingStore(BlobStore.java:112)
        at com.couchbase.lite.BlobStore.<init>(BlobStore.java:69)
        at com.couchbase.lite.BlobStoreTest.setUp(BlobStoreTest.java:59)
        at junit.framework.TestCase.runBare(TestCase.java:139)
        at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
        at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:77)
        at com.couchbase.lite.BlobStoreTest.runBare(BlobStoreTest.java:46)

com.couchbase.lite.BlobStoreTest > testBlobStoreWriter STANDARD_ERROR
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: LiteTestCaseWithDB: setUp
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger d
    FINE: Database: Starting Manager version: devbuild
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Opening com.couchbase.lite.Database[C:\Users\pasin\Git\couchbase-lite-java\data\data\com.couchbase.
lite.test\files\test\cblite-test.cblite2]
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: AndroidSQLCipherStorageEngine{database=79e240f0}: Opened Android sqlite db
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Begin transaction (level 0)
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Committing transaction (level 0)

com.couchbase.lite.BlobStoreTest > testBlobStoreWriter FAILED
    com.couchbase.lite.CouchbaseLiteException: Was not able to delete the database directory
        at com.couchbase.lite.Database.delete(Database.java:308)
        at com.couchbase.lite.LiteTestCaseWithDB.ensureEmptyDatabase(LiteTestCaseWithDB.java:179)
        at com.couchbase.lite.LiteTestCaseWithDB.startDatabase(LiteTestCaseWithDB.java:166)
        at com.couchbase.lite.LiteTestCaseWithDB.setUp(LiteTestCaseWithDB.java:97)
        at com.couchbase.lite.BlobStoreTest.setUp(BlobStoreTest.java:51)
        at junit.framework.TestCase.runBare(TestCase.java:139)
        at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
        at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:77)
        at com.couchbase.lite.BlobStoreTest.runBare(BlobStoreTest.java:43)

com.couchbase.lite.BlobStoreTest > testBlobStoreWriterBasicOperation STANDARD_ERROR
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: LiteTestCaseWithDB: setUp
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger d
    FINE: Database: Starting Manager version: devbuild
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Opening com.couchbase.lite.Database[C:\Users\pasin\Git\couchbase-lite-java\data\data\com.couchbase.
lite.test\files\test\cblite-test.cblite2]
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: AndroidSQLCipherStorageEngine{database=51d52040}: Opened Android sqlite db
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Begin transaction (level 0)
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Committing transaction (level 0)

com.couchbase.lite.BlobStoreTest > testBlobStoreWriterBasicOperation FAILED
    com.couchbase.lite.CouchbaseLiteException: Was not able to delete the database directory
        at com.couchbase.lite.Database.delete(Database.java:308)
        at com.couchbase.lite.LiteTestCaseWithDB.ensureEmptyDatabase(LiteTestCaseWithDB.java:179)
        at com.couchbase.lite.LiteTestCaseWithDB.startDatabase(LiteTestCaseWithDB.java:166)
        at com.couchbase.lite.LiteTestCaseWithDB.setUp(LiteTestCaseWithDB.java:97)
        at com.couchbase.lite.BlobStoreTest.setUp(BlobStoreTest.java:51)
        at junit.framework.TestCase.runBare(TestCase.java:139)
        at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
        at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:77)
        at com.couchbase.lite.BlobStoreTest.runBare(BlobStoreTest.java:43)

com.couchbase.lite.BlobStoreTest > testReopen STANDARD_ERROR
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: LiteTestCaseWithDB: setUp
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger d
    FINE: Database: Starting Manager version: devbuild
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Opening com.couchbase.lite.Database[C:\Users\pasin\Git\couchbase-lite-java\data\data\com.couchbase.
lite.test\files\test\cblite-test.cblite2]
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: AndroidSQLCipherStorageEngine{database=16d47954}: Opened Android sqlite db
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Begin transaction (level 0)
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Committing transaction (level 0)

com.couchbase.lite.BlobStoreTest > testReopen FAILED
    com.couchbase.lite.CouchbaseLiteException: Was not able to delete the database directory
        at com.couchbase.lite.Database.delete(Database.java:308)
        at com.couchbase.lite.LiteTestCaseWithDB.ensureEmptyDatabase(LiteTestCaseWithDB.java:179)
        at com.couchbase.lite.LiteTestCaseWithDB.startDatabase(LiteTestCaseWithDB.java:166)
        at com.couchbase.lite.LiteTestCaseWithDB.setUp(LiteTestCaseWithDB.java:97)
        at com.couchbase.lite.BlobStoreTest.setUp(BlobStoreTest.java:51)
        at junit.framework.TestCase.runBare(TestCase.java:139)
        at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
        at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:77)
        at com.couchbase.lite.BlobStoreTest.runBare(BlobStoreTest.java:43)

com.couchbase.lite.BlobStoreTest > testBlobStoreWriterForBody STANDARD_ERROR
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: LiteTestCaseWithDB: setUp
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger d
    FINE: Database: Starting Manager version: devbuild
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Opening com.couchbase.lite.Database[C:\Users\pasin\Git\couchbase-lite-java\data\data\com.couchbase.
lite.test\files\test\cblite-test.cblite2]
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: AndroidSQLCipherStorageEngine{database=18dd8196}: Opened Android sqlite db
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Begin transaction (level 0)
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Committing transaction (level 0)

com.couchbase.lite.BlobStoreTest > testBlobStoreWriterForBody FAILED
    com.couchbase.lite.CouchbaseLiteException: Was not able to delete the database directory
        at com.couchbase.lite.Database.delete(Database.java:308)
        at com.couchbase.lite.LiteTestCaseWithDB.ensureEmptyDatabase(LiteTestCaseWithDB.java:179)
        at com.couchbase.lite.LiteTestCaseWithDB.startDatabase(LiteTestCaseWithDB.java:166)
        at com.couchbase.lite.LiteTestCaseWithDB.setUp(LiteTestCaseWithDB.java:97)
        at com.couchbase.lite.BlobStoreTest.setUp(BlobStoreTest.java:51)
        at junit.framework.TestCase.runBare(TestCase.java:139)
        at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
        at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:77)
        at com.couchbase.lite.BlobStoreTest.runBare(BlobStoreTest.java:43)

com.couchbase.lite.BlobStoreTest > testLiteTestCaseSetupProperly STANDARD_ERROR
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: LiteTestCaseWithDB: setUp
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger d
    FINE: Database: Starting Manager version: devbuild
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Opening com.couchbase.lite.Database[C:\Users\pasin\Git\couchbase-lite-java\data\data\com.couchbase.
lite.test\files\test\cblite-test.cblite2]
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: AndroidSQLCipherStorageEngine{database=5dd6341a}: Opened Android sqlite db
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Begin transaction (level 0)
    Oct 01, 2015 4:45:16 AM com.couchbase.lite.util.SystemLogger v
    FINER: Database: Test worker Committing transaction (level 0)

com.couchbase.lite.BlobStoreTest > testLiteTestCaseSetupProperly FAILED
    com.couchbase.lite.CouchbaseLiteException: Was not able to delete the database directory
        at com.couchbase.lite.Database.delete(Database.java:308)
        at com.couchbase.lite.LiteTestCaseWithDB.ensureEmptyDatabase(LiteTestCaseWithDB.java:179)
        at com.couchbase.lite.LiteTestCaseWithDB.startDatabase(LiteTestCaseWithDB.java:166)
        at com.couchbase.lite.LiteTestCaseWithDB.setUp(LiteTestCaseWithDB.java:97)
        at com.couchbase.lite.BlobStoreTest.setUp(BlobStoreTest.java:51)
        at junit.framework.TestCase.runBare(TestCase.java:139)
        at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
        at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:77)
        at com.couchbase.lite.BlobStoreTest.runBare(BlobStoreTest.java:43)
Gradle Test Executor 1 finished executing tests.

6 tests completed, 6 failed
Finished generating test XML results (0.171 secs) into: C:\Users\pasin\Git\couchbase-lite-java\build\test-results
Generating HTML test report...
Finished generating test html results (0.094 secs) into: C:\Users\pasin\Git\couchbase-lite-java\build\reports\tests
:test FAILED
:test (Thread[main,5,main]) completed. Took 12.363 secs.

FAILURE: Build failed with an exception.
```

### PR DESCRIPTION
**Pull request by pasin**
Make sure that the FileInputStream gets closed in BlobStore.getBytesFromFile.

#771

### CODE REVIEW

**Comment by pasin** [comment]
@hideki have you had a chance to look at this?

File: src/main/java/com/couchbase/lite/BlobStore.java [hunk 1]
```diff
@@ -555,30 +554,33 @@ public boolean storeBlob(byte[] data, BlobKey outKey) {
...
 
-        // Get the size of the file
-        long length = file.length();
+            // Get the size of the file
+            long length = file.length();
 
-        // Create the byte array to hold the data
-        byte[] bytes = new byte[(int) length];
+            // Create the byte array to hold the data
+            byte[] bytes = new byte[(int) length];
```
Comment (hideki) [inline src/main/java/com/couchbase/lite/BlobStore.java]: This method loads entire content into the memory from the file. If a file is large, `new byte[length]` fails and return null. Should check return value from `new byte[length]`.

Comment (pasin) [inline src/main/java/com/couchbase/lite/BlobStore.java]: I'm not sure if this will return null or throw OOM exception. Probably this method needs rework. 

I believe you added this code in https://github.com/couchbase/couchbase-lite-java-core/commit/7e800559e9467b5173f89c8477b4ff68487f234e. Let handle this in a separated ticket.

Comment (pasin) [inline src/main/java/com/couchbase/lite/BlobStore.java]: https://github.com/couchbase/couchbase-lite-java-core/issues/781

**Comment by zgramana** [comment]
This really should get refactored to use a fixed length buffer to keep memory usage well-bounded.
