### PR TITLE
Fixed #1074 - Enhance logging information for replicator and set thre…

### LINKED ISSUE #1074: Enhance logging information of replicator thread
Thread-dump:
- `"CBLRequestWorker-5ed49-1@23800" prio=5 runnable` 
- `"CBLPusherInternalExecutor-42@23798" prio=9 waiting`

Logging:
- `02-29 16:05:31.278   6023-16591/com.sample.app V/Sync﹕ com.couchbase.lite.replicator.PusherInternal@25371662: addToInbox() called, rev: {172.23.8.22 #378-7a75f3d85fac235ff36b823345415d17}.  Thread: Thread[CBLPusherInternalExecutor-44,5,main]`
-`com.couchbase.lite.support.RemoteRequest@2495b4c1: RemoteRequest finally block.  url: http://172.23.8.24:5984/ek0073/_revs_diff`
- `02-29 16:05:31.788   6023-16481/com.sample.app I/System.out﹕ CBLRequestWorker-5ed49-0 calls detatch()`
- `com.couchbase.lite.replicator.ChangeTracker@3a2ce72a: Exception in change tracker
    java.net.SocketTimeoutException`

### PR DESCRIPTION
**Pull request by hideki**
…ad name to replicator related threads.

- Set thread name to all replicator related thread.
- Add `toString()` for replicator related classes to track log information easily.

### CODE REVIEW

File: src/main/java/com/couchbase/lite/replicator/PullerInternal.java [hunk 1]
```diff
@@ -1032,4 +1036,17 @@ protected void pauseOrResume() {
...
     }
+
+    @Override
+    public String toString() {
+        if (str == null) {
+            String maskedRemote = remote.toExternalForm();
+            maskedRemote = maskedRemote.replaceAll("://.*:.*@", "://---:---@");
+            String type = parentReplication.isPull() ? "pull" : "push";
+            String replicationIdentifier = Utils.shortenString(remoteCheckpointDocID(), 5);
+            str = String.format("PusherInternal{%s, %s, %s}",
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/PullerInternal.java]: Is it PullerInternal?

**Comment by hideki** [comment]
@pasin sorry for my mistake.
