### PR TITLE
Fixed #1483 - OOM by /_changes RET API with too many document changes.

### LINKED ISSUE #1483: 1.x: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 329648 free bytes and 321KB until OOM; failed due to fragmentation...
**Trying to sync ~380,000 documents with no attachments**

App keeps crashing. I think it synced about ~150,000 and now it crashes every 10 seconds. Tried restarting the device, and force closing app. 

Cordova/Ionic App
Current App Size: 2.71 GB

Device: Asus Tablet P00A
Total Memory: 1.9 GB
Android: 6.0

**Is there a limit to how many documents a device can handle?**

```
Uncaught exception thrown by finalizer
10-14 11:59:26.762 6086-6094/? E/System: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 329648 free bytes and 321KB until OOM; failed due to fragmentation (required continguous free 4096 bytes for a new buffer where largest contiguous free 0 bytes)
      at com.android.internal.os.BinderInternal$GcWatcher.finalize(BinderInternal.java:53)
      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:228)
      at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:206)
      at java.lang.Thread.run(Thread.java:818)

10-14 11:59:26.762 6086-6094/? I/System: FinalizerDaemon: finalize objects = 26
10-14 11:59:26.792 6086-6181/? I/art: Alloc concurrent mark sweep GC freed 774(51KB) AllocSpace objects, 0(0B) LOS objects, 37% free, 6MB/10MB, paused 1.365ms total 31.195ms
10-14 11:59:26.793 6086-6177/? I/art: WaitForGcToComplete blocked for 724.833ms for cause Alloc
10-14 11:59:26.793 6086-6177/? I/art: Starting a blocking GC Alloc
10-14 11:59:26.793 6086-6096/? I/art: WaitForGcToComplete blocked for 9.500s for cause HeapTrim
10-14 11:59:26.793 6086-6095/? I/art: Waiting for a blocking GC Alloc
10-14 11:59:26.793 6086-6212/? I/art: Waiting for a blocking GC Alloc
10-14 11:59:26.793 6086-6203/? I/art: Waiting for a blocking GC Alloc

10-14 11:59:26.793 6086-6177/? W/Router: Router unable to route request to do_GET_Document_changes
  java.lang.reflect.InvocationTargetException
      at java.lang.reflect.Method.invoke(Native Method)
      at com.couchbase.lite.router.Router.start(Router.java:556)
      at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
      at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
      at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
      at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
      at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
      at java.lang.Thread.run(Thread.java:818)
   Caused by: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
10-14 11:59:26.793 6086-6183/? I/art: Waiting for a blocking GC Alloc
```

### PR DESCRIPTION
**Pull request by hideki**
Original Title: 1.x: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 329648 free bytes and 321KB until OOM; failed due to fragmentation...

- ~~Set 10000 to changes limit of  REST API (Default value was Integer.MAX_VALUE, and Native API's default value is not changed)~~
- Ported `limit` method parameter to `responseBodyForChangesWithConflicts()` method in case results from DB is more than limit.

### CODE REVIEW

File: src/main/java/com/couchbase/lite/router/Router.java [hunk 1]
```diff
@@ -88,6 +88,10 @@
 
     private static final String CONTENT_TYPE_JSON = "application/json";
 
+    // Android cannot hold unlimited changes data.
+    // See ChangesOptions.limit default value (Integer.MAX_VALUE)
+    public static final int DEF_CHANGES_LIMIT = 10000;
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/router/Router.java]: Does this have a side effect to one-short pull replicator for P2P? I don't know if there is a better fix or not, but each device / platform has different memory limitation. Just want to know if the users do this by themselves?

Comment (hideki) [reply src/main/java/com/couchbase/lite/router/Router.java]: @pasin Thanks for pointing about the oneshot pull replication peer-to-peer scenario. I will test one shot and continuous pull replication.

**Comment by hideki** [comment]
@pasin, I removed default limit value change for /_changes REST API. Please review this ticket. Thanks!
