### PR TITLE
Fixed #452 - Error after close DB client

### LINKED ISSUE #452: Error after close DB client
https://github.com/couchbase/couchbase-lite-java/issues/52

```java
private void shutdownDatabase() {
        push.goOffline();
        pull.goOffline();
        pull.stop();
        push.stop();
        database.close();
        manager.close();
    }
````
in log:
```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@32f4b68 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@5263919f[Shutting down, pool size = 1, active threads = 1, queued tasks = 6, completed tasks = 15]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
	at com.couchbase.lite.replicator.PullerInternal.changeTrackerStopped(PullerInternal.java:766)
	at com.couchbase.lite.replicator.ChangeTracker.stopped(ChangeTracker.java:512)
	at com.couchbase.lite.replicator.ChangeTracker.stop(ChangeTracker.java:498)
	at com.couchbase.lite.replicator.PullerInternal.goOffline(PullerInternal.java:994)
	at com.couchbase.lite.replicator.ReplicationInternal$15.doIt(ReplicationInternal.java:1101)
	at com.couchbase.lite.replicator.ReplicationInternal$15.doIt(ReplicationInternal.java:1098)
	at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:130)
	at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:127)
	at com.github.oxo42.stateless4j.StateRepresentation.executeEntryActions(StateRepresentation.java:123)
	at com.github.oxo42.stateless4j.StateRepresentation.enter(StateRepresentation.java:102)
	at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:199)
	at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:125)
	at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:191)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4579bbfb rejected from java.util.concurrent.ScheduledThreadPoolExecutor@5263919f[Shutting down, pool size = 1, active threads = 1, queued tasks = 3, completed tasks = 18]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
	at com.couchbase.lite.replicator.ReplicationInternal.notifyChangeListeners(ReplicationInternal.java:983)
	at com.couchbase.lite.replicator.ReplicationInternal.notifyChangeListenersStateTransition(ReplicationInternal.java:1138)
	at com.couchbase.lite.replicator.ReplicationInternal.access$400(ReplicationInternal.java:61)
	at com.couchbase.lite.replicator.ReplicationInternal$16.doIt(ReplicationInternal.java:1109)
	at com.couchbase.lite.replicator.ReplicationInternal$16.doIt(ReplicationInternal.java:1105)
	at com.github.oxo42.stateless4j.StateRepresentation.executeExitActions(StateRepresentation.java:130)
	at com.github.oxo42.stateless4j.StateRepresentation.exit(StateRepresentation.java:112)
	at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:197)
	at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:125)
	at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:191)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by hideki**
Fixed #452 - Error after close DB client

Problem:
- Executor which is used in Manager and ReplicatorInternal caused thread leak, it requires to call shutdown() method.

Solution:
- Shuts down Executor Thread which is created by Manager
- Shuts down Executor Thread which is created by Replicator
- Wait all replicators become STOPPED state in Database.close()
- Implements two phases Executor shutdown
- Applied code style to Manager.java and Utils.java

### CODE REVIEW

File: src/main/java/com/couchbase/lite/Database.java [hunk 1]
```diff
@@ -1152,27 +1149,54 @@ private void markBlobstoreMigrated() {
...
+                            latch.countDown();
+                        }
+                    }
+                });
+                latches.add(latch);
+
+                // ask replicator to stop
                 replicator.databaseClosing();
             }
+
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/Database.java]: 1. As I don't fully understand the threading model of the java replicators, I assume that this code snippet is thread-safe (e.g. it's not possible that a replicator stopped while adding a change listener to that replicator). Can you confirm that?

2. As we are going to wait until all of the replicators to be done, it's really unknown to me that this is going to pause the app if I call database.close() in my app. What is your opinion on this? Honestly I need to try this with the CBL iOS as well to see the current behavior.

I don't fully understand the replicator stopping chains. @tleyden can you review this part as well?

File: src/main/java/com/couchbase/lite/util/Utils.java [hunk 2]
```diff
@@ -165,78 +170,122 @@ public static String shortenString(String orig, int maxLength) {
...
+     * The following method shuts down an ExecutorService in two phases,
+     * first by calling shutdown to reject incoming tasks, and then calling shutdownNow,
+     * if necessary, to cancel any lingering tasks:
+     * http://docs.oracle.com/javase/6/docs/api/java/util/concurrent/ExecutorService.html
+     */
+    public static void shutdownAndAwaitTermination(ExecutorService pool) {
+        pool.shutdown(); // Disable new tasks from being submitted
+        try {
+            // Wait a while for existing tasks to terminate
+            if (!pool.awaitTermination(60, TimeUnit.SECONDS)) {
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/util/Utils.java]: In database.close() above, we are waiting for 20 seconds but here we are waiting for 60 seconds to force termination. Should the number here lower that 20 seconds or should the database.close() wait for me than 60 seconds?

File: src/main/java/com/couchbase/lite/Database.java (hunk 1 above)
Comment (tleyden) [inline src/main/java/com/couchbase/lite/Database.java]: Ok

File: src/main/java/com/couchbase/lite/util/Utils.java (hunk 2 above)
Comment (hideki) [inline src/main/java/com/couchbase/lite/util/Utils.java]: I will apply 20 sec for both cases. And I will keep eye open if 20 sec is good value.

File: src/main/java/com/couchbase/lite/Database.java (hunk 1 above)
Comment (hideki) [inline src/main/java/com/couchbase/lite/Database.java]: Response for question 1:
- In general, Database class is not thread safe. Only `open()` method is `synchronized` method to protected SQLite database. From the code, I consider that `close()` method is not necessary to be synchronized method. For safety, we can apply `synchronized`.

- Regarding SQLiteDatabase (SQLite), it provides a locking mechanism by default. So storage is thread safe.
http://stackoverflow.com/questions/6675240/is-sqlite-database-instance-thread-safe
http://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#setLockingEnabled%28boolean%29

Comment (hideki) [inline src/main/java/com/couchbase/lite/Database.java]: Response for question 2:
- If user calls Database.close() from UI thread, it might cause UI freezing state for 20 sec maximum. SQLiteDatabase.close() does not block, it just release references.
- However, Database.close() is annotated with `@InterfaceAudience.Private`. So user should not call this directly.
- We could provide non-blocking Database close() method if necessary.

Comment (pasin) [inline src/main/java/com/couchbase/lite/Database.java]: For #1, what I mean is that if activeReplicators property is not thread-safe, there could be a case that while setting up the change listener for a replicator, that replicator might be stopped due to some reasons (e.g. permanent error or finish replicating (non-continuous)) -- actually if that happens, there will be a runtime exception thrown for iterating over a changed array.

**Comment by tleyden** [comment]
I'm seeing a [unit test failure](http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-build/65/console) on Jenkins:

```
com.couchbase.lite.ManagerTest > testClose[hudson_en-US_160_WVGA_android-19_armeabi-v7a_param(AVD) - 4.4.2] [31mFAILED [0m
	junit.framework.AssertionFailedError: expected:<0> but was:<1>
	at com.couchbase.lite.ManagerTest.testClose(ManagerTest.java:229)
```

**Comment by tleyden** [comment]
Also seeing a unit test failure locally: https://github.com/couchbase/couchbase-lite-android/issues/544  (not sure if its related to this change though)

**Comment by hideki** [comment]
I believe unit test failure on Jenkins could be caused by pointing old CBL java core submodule. I updated submodule, and restart Jenkins: http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-build/67/

**Comment by hideki** [comment]
Unit Test failure on Jenkins server
http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-build/67/console
```
com.couchbase.lite.replicator.ChangeTrackerTest > testChangeTrackerBackoffExceptions[hudson_en-US_160_WVGA_android-19_armeabi-v7a_param(AVD) - 4.4.2] [31mFAILED [0m
	junit.framework.AssertionFailedError
	at com.couchbase.lite.replicator.ChangeTrackerTest.testChangeTrackerBackoff(ChangeTrackerTest.java:356)

com.couchbase.lite.replicator.ChangeTrackerTest > testChangeTrackerBackoffInvalidJson[hudson_en-US_160_WVGA_android-19_armeabi-v7a_param(AVD) - 4.4.2] [31mFAILED [0m
	junit.framework.AssertionFailedError
	at com.couchbase.lite.replicator.ChangeTrackerTest.testChangeTrackerBackoff(ChangeTrackerTest.java:356)

com.couchbase.lite.replicator.ReplicationTest > testMockPullBulkDocsSyncGw[hudson_en-US_160_WVGA_android-19_armeabi-v7a_param(AVD) - 4.4.2] [31mFAILED [0m
	junit.framework.AssertionFailedError
	at com.couchbase.lite.replicator.ReplicationTest.mockPullBulkDocs(ReplicationTest.java:3383)
```

**Comment by tleyden** [comment]
It looks like the test failures are happening on master too: http://172.23.113.52:8080/job/couchbase-lite-android-build/66/console

So probably not related to this PR

**Comment by hideki** [comment]
I will create new ticket for ChangeTracker unit test failure on Jenkins
