### PR TITLE
Fixed #498 - Pull replication failure which caused by stub Attachment with many revisions

### LINKED ISSUE #498: Sync fails to complete initial sync when in continuous mode
Greetings,

Continuous mode of sync seems to have some issues. I currently can not complete a full sync if the pull replicator is in continuous mode and the replicator seems to display some odd behavior.

I get through quite a few documents but currently I'm seeing the end result being 
```
03-16 13:37:45.930  25445-25483/com.app.appmobile.alpha E/Sync﹕ Change tracker stopped during continuous replication
03-16 13:37:45.930  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
03-16 13:37:45.930  25445-25483/com.app.appmobile.alpha D/app﹕ Replicator last error: java.lang.Exception: Change tracker stopped during continuous replication -> Change tracker stopped during continuous replication / Change tracker stopped during continuous replication
03-16 13:37:45.930  25445-25483/com.app.appmobile.alpha D/app﹕ Stopping all replications.
03-16 13:37:45.930  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:45.930  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:45.930  25445-25483/com.app.appmobile.alpha D/app﹕ Replicator last error: java.lang.Exception: Change tracker stopped during continuous replication -> Change tracker stopped during continuous replication / Change tracker stopped during continuous replication
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha D/app﹕ Stopping all replications.
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha D/app﹕ Replicator last error: java.lang.Exception: Change tracker stopped during continuous replication -> Change tracker stopped during continuous replication / Change tracker stopped during continuous replication
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha D/app﹕ Stopping all replications.
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha D/app﹕ Replicator last error: java.lang.Exception: Change tracker stopped during continuous replication -> Change tracker stopped during continuous replication / Change tracker stopped during continuous replication
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha D/app﹕ Stopping all replications.
03-16 13:37:45.950  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:45.950  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:46.190  25445-25500/com.app.appmobile.alpha W/Sync﹕ com.couchbase.lite.replicator.ReplicationInternal$7@4213af50: Database is null or closed, not calling db.setLastSequence()
03-16 13:37:46.190  25445-26067/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
03-16 13:37:46.240  25445-25483/com.app.appmobile.alpha D/app﹕ Replicator last error: java.lang.Exception: Change tracker stopped during continuous replication -> Change tracker stopped during continuous replication / Change tracker stopped during continuous replication
03-16 13:37:46.240  25445-25483/com.app.appmobile.alpha D/app﹕ Stopping all replications.
```

The pull replicator is also emitting callbacks during replication stating it's idle with 0/0 documents somewhat randomly, which is incorrect behavior. Possibly related to #456 .

Thanks,
Justin

### PR DESCRIPTION
**Pull request by hideki**

### CODE REVIEW

File: src/main/java/com/couchbase/lite/Database.java [hunk 1]
```diff
@@ -4064,18 +4075,40 @@ else if (attachInfo.containsKey("follows") && ((Boolean)attachInfo.get("follows"
...
+                    }
+                    if (getAttachments().hasBlobForKey(blobKey)) {
+                        attachment.setBlobKey(blobKey);
+                    } else {
+                        continue;
+                    }
+                } else {
+                    continue;
+                }
             }
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/Database.java]: I understand that the code here injects the attachment with the blob key generated by the digest from the attachment info. When the processAttachmentsForRevision method is later called, the copyAttachmentNamedFromSequenceToSequence() method will not get called as the attachment does already exist.

However there is one thing that I'm not so sure is the revpos set in the processAttachmentsForRevision() method. I think it will set the revpos to the current revision instead of the one from the attachment info (Could you be confirm which revpos it will be set?). Honestly I don't know if it is matter or not.

Comment (hideki) [inline src/main/java/com/couchbase/lite/Database.java]: `revpos` is set later at Line 4129-4131. It is common operation for all kinds of attachments.
https://github.com/couchbase/couchbase-lite-java-core/blob/feature/issue_498_sync_fail/src/main/java/com/couchbase/lite/Database.java#L4129-L4131
