### PR TITLE
Fixed #824 - BulkDownloader[/db/_bulk_get]: executeRequest() Exceptio…

### LINKED ISSUE #824: BulkDownloader[/db/_bulk_get]: executeRequest() Exception:  java.lang.IllegalStateException: _docReader is not defined
from sg functional tests

http://qa.sc.couchbase.com/view/mobile/job/centos-sync-gateway-mobile-functional-tests-android-cb/lastSuccessfulBuild/artifact/01_adb.log

```
11-18 10:58:02.589 I/art     ( 2084): Background sticky concurrent mark sweep GC freed 4607(439KB) AllocSpace objects, 26(560KB) LOS objects, 20% free, 4MB/5MB, paused 7.146ms total 191.294ms
11-18 10:58:02.895 W/Sync    ( 2084): com.couchbase.lite.replicator.PullerInternal@f67f833: Received invalid doc ID from _changes: {seq=1, id=_user/, changes=[{rev=}]}
11-18 10:58:03.153 W/Sync    ( 2084): com.couchbase.lite.replicator.PusherInternal@19fd7b8d: removePending: sequence 1610 not in set, for rev {large-revisions-revslimit_9 #161-9dc57942fd1f76fbb39ea872f8082ff2}
11-18 10:58:03.575 E/RemoteRequest( 2084): com.couchbase.lite.replicator.BulkDownloader[/db/_bulk_get]: executeRequest() Exception: 
11-18 10:58:03.575 E/RemoteRequest( 2084): java.lang.IllegalStateException: _docReader is not defined
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at com.couchbase.lite.replicator.BulkDownloader.appendToPart(BulkDownloader.java:239)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at com.couchbase.lite.support.MultipartReader.trimBuffer(MultipartReader.java:123)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at com.couchbase.lite.support.MultipartReader.appendData(MultipartReader.java:177)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at com.couchbase.lite.replicator.BulkDownloader.executeRequest(BulkDownloader.java:148)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at com.couchbase.lite.replicator.BulkDownloader.run(BulkDownloader.java:89)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at java.lang.Thread.run(Thread.java:818)
11-18 10:58:03.589 E/Sync    ( 2084): com.couchbase.lite.replicator.PullerInternal@f67f833: Progress: set error = java.lang.IllegalStateException: _docReader is not defined
11-18 10:58:04.223 I/art     ( 2084): Background partial concurrent mark sweep GC freed 19836(3MB) AllocSpace objects, 2(128KB) LOS objects, 24% free, 2MB/2MB, paused 3.364ms total 266.447ms
11-18 10:58:04.705 E/RemoteRequest( 2084): com.couchbase.lite.replicator.BulkDownloader[/db/_bulk_get]: executeRequest() Exception: 
11-18 10:58:04.705 E/RemoteRequest( 2084): java.lang.IllegalStateException: _docReader is not defined
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at com.couchbase.lite.replicator.BulkDownloader.appendToPart(BulkDownloader.java:239)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at com.couchbase.lite.support.MultipartReader.trimBuffer(MultipartReader.java:123)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at com.couchbase.lite.support.MultipartReader.appendData(MultipartReader.java:177)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at com.couchbase.lite.replicator.BulkDownloader.executeRequest(BulkDownloader.java:148)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at com.couchbase.lite.replicator.BulkDownloader.run(BulkDownloader.java:89)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at java.lang.Thread.run(Thread.java:818)
11-18 10:58:04.706 E/Sync    ( 2084): com.couchbase.lite.replicator.PullerInternal@f67f833: Progress: set error = java.lang.IllegalStateException: _docReader is not defined
```

### PR DESCRIPTION
**Pull request by hideki**
…n: java.lang.IllegalStateException: _docReader is not defined

Problem:  Sync Gateway fixed https://github.com/couchbase/sync_gateway/issues/1163 which is to gzip encode entire response for _bulk_get REST api if Accept-Encoding is gzip. Previously Sync Gateway gzipped multi-part document independently. Android did not support entire gzipped encoding for _bulk_get.

Solution: Decode gzipped response for _bulk_get if it is gzipped.

### CODE REVIEW

File: src/main/java/com/couchbase/lite/replicator/BulkDownloader.java [hunk 1]
```diff
@@ -134,47 +136,45 @@ protected void executeRequest(HttpClient httpClient, HttpUriRequest request) {
...
-                                    _topReader = new MultipartReader(contentTypeHeader.getValue(), this);
-                                    byte[] buffer = new byte[BUF_LEN];
-                                    int numBytesRead = 0;
-                                    while ((numBytesRead = inputStream.read(buffer)) != -1) {
-                                        _topReader.appendData(buffer, 0, numBytesRead);
+                            GZIPInputStream gzipStream = null;
+                            try {
+                                Header contentTypeHeader = entity.getContentType();
+                                if (contentTypeHeader != null) {
+                                    // decompress if contentEncoding is gzip
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/BulkDownloader.java]: If contentTypeHeader is null, the inputStream created at line 138 doesn't get used. Can we move `inputStream = entity.getContent();` inside the `if (contentTypeHeader != nulll)` block?

File: src/main/java/com/couchbase/lite/replicator/BulkDownloader.java [hunk 2]
```diff
@@ -134,47 +136,45 @@ protected void executeRequest(HttpClient httpClient, HttpUriRequest request) {
...
+                                                contentTypeHeader.getValue());
+                                        fullBody = Manager.getObjectMapper().readValue(
+                                                inputStream, Object.class);
+                                        respondWithResult(fullBody, error, response);
+                                    }
+                                }
+                            } finally {
+                                try {
+                                    if (gzipStream != null) {
+                                        gzipStream.close();
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/BulkDownloader.java]: In line 146, gzipStream was assigned to inputStream variable, the inputStream will be closed in the outer finally block below. So closing gzipStream here is redundant.

File: src/main/java/com/couchbase/lite/replicator/BulkDownloader.java (hunk 1 above)
Comment (hideki) [inline src/main/java/com/couchbase/lite/replicator/BulkDownloader.java]: I will fix this.

File: src/main/java/com/couchbase/lite/replicator/BulkDownloader.java (hunk 2 above)
Comment (hideki) [inline src/main/java/com/couchbase/lite/replicator/BulkDownloader.java]: `GZIPInputStream ` closes parent `InputStream` by calling `close()`. I will remove nested `try{}finally{}` block.

**Comment by hideki** [comment]
@pasin Could you please review PR again?
