### PR TITLE
Fixed #736 - Add retry queue for failed revisions in a bulk get

### LINKED ISSUE #736: Add retry queue for failed revisions in a bulk get

### PR DESCRIPTION
**Pull request by hideki**
Ported C# codes from https://github.com/couchbase/couchbase-lite-net/pull/454

### CODE REVIEW

File: src/main/java/com/couchbase/lite/replicator/PullerInternal.java [hunk 1]
```diff
@@ -334,7 +336,17 @@ public void onCompletion(HttpResponse httpResponse, Object result, Throwable e)
                             // The entire _bulk_get is finished:
                             if (e != null) {
                                 setError(e);
-                                completedChangesCount.addAndGet(remainingRevs.size());
+                                Log.e(TAG, "RemoteRequestCompletionBlock: remainingRevs.size()=" + remainingRevs.size());
+                                //completedChangesCount.addAndGet(remainingRevs.size());
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/PullerInternal.java]: This can be deleted.

File: src/main/java/com/couchbase/lite/support/CouchbaseLiteHttpClientFactory.java [hunk 2]
```diff
@@ -41,9 +41,9 @@
     private SSLSocketFactory sslSocketFactory;
 
     private BasicHttpParams basicHttpParams;
-
-    public static final int DEFAULT_CONNECTION_TIMEOUT_SECONDS = 60;
-    public static final int DEFAULT_SO_TIMEOUT_SECONDS = 60 * 5;
+    
+    public static int DEFAULT_CONNECTION_TIMEOUT_SECONDS = 60;
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/support/CouchbaseLiteHttpClientFactory.java]: Why removing final? Do we just it anywhere?

File: src/main/java/com/couchbase/lite/replicator/PullerInternal.java [hunk 3]
```diff
@@ -361,6 +373,48 @@ public void onCompletion(HttpResponse httpResponse, Object result, Throwable e)
         }
     }
 
+    /**
+     * BulkDownloader HTTP request timeouts not properly handled
+     * https://github.com/couchbase/couchbase-lite-net/issues/356
+     */
+    private boolean shouldRetryDownload(String docId) {
+        Log.e(TAG, "shouldRetryDownload: " + docId);
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/PullerInternal.java]: Shouldn't be Log.e.

File: src/main/java/com/couchbase/lite/replicator/PullerInternal.java [hunk 4]
```diff
@@ -361,6 +373,48 @@ public void onCompletion(HttpResponse httpResponse, Object result, Throwable e)
...
+        try {
+            getLocalDatabase().putLocalDocument(docId, localDoc);
+        } catch (CouchbaseLiteException e) {
+            Log.w(TAG, "Failed to store retryCount value for docId: " + docId, e);
+        }
+        return true;
+    }
+
+    private void pruneFailedDownload(String docId) {
+        Log.e(TAG, "pruneFailedDownload: " + docId);
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/PullerInternal.java]: Shouldn't be Log.e.

File: src/main/java/com/couchbase/lite/replicator/PullerInternal.java [hunk 5]
```diff
@@ -334,7 +336,17 @@ public void onCompletion(HttpResponse httpResponse, Object result, Throwable e)
                             // The entire _bulk_get is finished:
                             if (e != null) {
                                 setError(e);
-                                completedChangesCount.addAndGet(remainingRevs.size());
+                                Log.e(TAG, "RemoteRequestCompletionBlock: remainingRevs.size()=" + remainingRevs.size());
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/PullerInternal.java]: The log message doesn't refer to the error. Should it be Log.v instead?

File: src/main/java/com/couchbase/lite/replicator/PullerInternal.java [hunk 6]
```diff
@@ -334,7 +336,17 @@ public void onCompletion(HttpResponse httpResponse, Object result, Throwable e)
...
+                                //completedChangesCount.addAndGet(remainingRevs.size());
+                                for (int i = 0; i < remainingRevs.size(); i++) {
+                                    RevisionInternal rev = remainingRevs.get(i);
+                                    Log.e(TAG, "RemoteRequestCompletionBlock: rev="+rev);
```
Comment (pasin) [inline src/main/java/com/couchbase/lite/replicator/PullerInternal.java]: Same as above. The log message doesn't refer to the error. Should it be Log.v instead?

File: src/main/java/com/couchbase/lite/support/CouchbaseLiteHttpClientFactory.java (hunk 2 above)
Comment (hideki) [inline src/main/java/com/couchbase/lite/support/CouchbaseLiteHttpClientFactory.java]: For unit test purpose, I removed `final` keyword form these constants.

**Comment by hideki** [comment]
@pasin Please review this PR again?
